# Generated by Django 5.0.14 on 2025-10-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutors',
            name='userName',
        ),
        migrations.AddField(
            model_name='tutors',
            name='username',
            field=models.CharField(default='temp', max_length=20),
        ),
    ]
