# Generated by Django 5.0.14 on 2025-10-17 15:45

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_tutors_username_tutors_username'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutors',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='tutors',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='tutors',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='tutors',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tutors',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='tutors',
            name='username',
        ),
        migrations.AddField(
            model_name='tutors',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
