# Generated by Django 5.0.14 on 2025-10-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_tutors_options_alter_tutors_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutors',
            name='days_tutor_for',
            field=models.CharField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thrusday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')], default='1', max_length=7),
        ),
    ]
