# Generated by Django 5.0.14 on 2025-10-17 15:59

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_tutors_days_tutor_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutors',
            name='days_tutor_for',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thrusday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')], max_length=13),
        ),
    ]
