# Generated by Django 5.0.14 on 2025-10-17 19:35

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_tutors_classes_tutor_for'),
    ]

    operations = [
        migrations.CreateModel(
            name='hours_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_tutor_for', multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thrusday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')], max_length=13)),
                ('hours', multiselectfield.db.fields.MultiSelectField(choices=[('1', '8am-9am'), ('2', '9am-10am'), ('3', '10am-11am'), ('4', '11am-12am'), ('5', '12am-1pm'), ('6', '1pm-2pm'), ('7', '3pm-4pm'), ('8', '4pm-5pm'), ('9', '5pm-6pm')], max_length=17)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.tutors')),
            ],
        ),
    ]
