# Generated by Django 5.0.14 on 2025-10-18 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_tutors_classes_tutor_for'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutors',
            name='hours_tutor_for',
        ),
        migrations.AddField(
            model_name='tutors',
            name='hours_tutor_for_mon',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
