# Generated by Django 5.0.14 on 2025-10-17 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_hours_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hours_model',
            name='day_tutor_for',
        ),
    ]
