# Generated by Django 5.0.14 on 2025-10-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_remove_tutors_hours_tutor_for_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutors',
            name='hours_tutor_for_fri',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tutors',
            name='hours_tutor_for_sat',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tutors',
            name='hours_tutor_for_sun',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tutors',
            name='hours_tutor_for_thr',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tutors',
            name='hours_tutor_for_tue',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tutors',
            name='hours_tutor_for_wed',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
