# Generated by Django 5.0.14 on 2025-10-19 16:08

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_tutors_hours_tutor_for_fri_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutors',
            name='hours_tutor_for_fri',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('7', '7-8am'), ('8', '8-9am'), ('9', '9-10am'), ('10', '10-11am'), ('11', '11-12pm'), ('12', '12-1pm'), ('13', '1-2pm'), ('14', '2-3pm'), ('15', '3-4pm'), ('16', '4-5pm'), ('17', '5-6pm')], max_length=29),
        ),
        migrations.AlterField(
            model_name='tutors',
            name='hours_tutor_for_mon',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('7', '7-8am'), ('8', '8-9am'), ('9', '9-10am'), ('10', '10-11am'), ('11', '11-12pm'), ('12', '12-1pm'), ('13', '1-2pm'), ('14', '2-3pm'), ('15', '3-4pm'), ('16', '4-5pm'), ('17', '5-6pm')], max_length=29),
        ),
        migrations.AlterField(
            model_name='tutors',
            name='hours_tutor_for_sat',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('7', '7-8am'), ('8', '8-9am'), ('9', '9-10am'), ('10', '10-11am'), ('11', '11-12pm'), ('12', '12-1pm'), ('13', '1-2pm'), ('14', '2-3pm'), ('15', '3-4pm'), ('16', '4-5pm'), ('17', '5-6pm')], max_length=29),
        ),
        migrations.AlterField(
            model_name='tutors',
            name='hours_tutor_for_sun',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('7', '7-8am'), ('8', '8-9am'), ('9', '9-10am'), ('10', '10-11am'), ('11', '11-12pm'), ('12', '12-1pm'), ('13', '1-2pm'), ('14', '2-3pm'), ('15', '3-4pm'), ('16', '4-5pm'), ('17', '5-6pm')], max_length=29),
        ),
        migrations.AlterField(
            model_name='tutors',
            name='hours_tutor_for_thr',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('7', '7-8am'), ('8', '8-9am'), ('9', '9-10am'), ('10', '10-11am'), ('11', '11-12pm'), ('12', '12-1pm'), ('13', '1-2pm'), ('14', '2-3pm'), ('15', '3-4pm'), ('16', '4-5pm'), ('17', '5-6pm')], max_length=29),
        ),
        migrations.AlterField(
            model_name='tutors',
            name='hours_tutor_for_tue',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('7', '7-8am'), ('8', '8-9am'), ('9', '9-10am'), ('10', '10-11am'), ('11', '11-12pm'), ('12', '12-1pm'), ('13', '1-2pm'), ('14', '2-3pm'), ('15', '3-4pm'), ('16', '4-5pm'), ('17', '5-6pm')], max_length=29),
        ),
        migrations.AlterField(
            model_name='tutors',
            name='hours_tutor_for_wed',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('7', '7-8am'), ('8', '8-9am'), ('9', '9-10am'), ('10', '10-11am'), ('11', '11-12pm'), ('12', '12-1pm'), ('13', '1-2pm'), ('14', '2-3pm'), ('15', '3-4pm'), ('16', '4-5pm'), ('17', '5-6pm')], max_length=29),
        ),
    ]
