# Generated by Django 5.0.14 on 2025-10-17 19:49

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_tutors_hours1_tutors_hours2_tutors_hours3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutors',
            name='hours2',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', '8am-9am'), ('2', '9am-10am'), ('3', '10am-11am'), ('4', '11am-12am'), ('5', '12am-1pm'), ('6', '1pm-2pm'), ('7', '3pm-4pm'), ('8', '4pm-5pm'), ('9', '5pm-6pm')], max_length=17),
        ),
        migrations.AlterField(
            model_name='tutors',
            name='hours3',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', '8am-9am'), ('2', '9am-10am'), ('3', '10am-11am'), ('4', '11am-12am'), ('5', '12am-1pm'), ('6', '1pm-2pm'), ('7', '3pm-4pm'), ('8', '4pm-5pm'), ('9', '5pm-6pm')], max_length=17),
        ),
        migrations.AlterField(
            model_name='tutors',
            name='hours4',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', '8am-9am'), ('2', '9am-10am'), ('3', '10am-11am'), ('4', '11am-12am'), ('5', '12am-1pm'), ('6', '1pm-2pm'), ('7', '3pm-4pm'), ('8', '4pm-5pm'), ('9', '5pm-6pm')], max_length=17),
        ),
        migrations.AlterField(
            model_name='tutors',
            name='hours5',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', '8am-9am'), ('2', '9am-10am'), ('3', '10am-11am'), ('4', '11am-12am'), ('5', '12am-1pm'), ('6', '1pm-2pm'), ('7', '3pm-4pm'), ('8', '4pm-5pm'), ('9', '5pm-6pm')], max_length=17),
        ),
        migrations.AlterField(
            model_name='tutors',
            name='hours6',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', '8am-9am'), ('2', '9am-10am'), ('3', '10am-11am'), ('4', '11am-12am'), ('5', '12am-1pm'), ('6', '1pm-2pm'), ('7', '3pm-4pm'), ('8', '4pm-5pm'), ('9', '5pm-6pm')], max_length=17),
        ),
        migrations.AlterField(
            model_name='tutors',
            name='hours7',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', '8am-9am'), ('2', '9am-10am'), ('3', '10am-11am'), ('4', '11am-12am'), ('5', '12am-1pm'), ('6', '1pm-2pm'), ('7', '3pm-4pm'), ('8', '4pm-5pm'), ('9', '5pm-6pm')], max_length=17),
        ),
    ]
