# Generated by Django 5.0.14 on 2025-10-17 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_alter_tutors_hours2_alter_tutors_hours3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutors',
            name='hours1',
        ),
        migrations.RemoveField(
            model_name='tutors',
            name='hours2',
        ),
        migrations.RemoveField(
            model_name='tutors',
            name='hours3',
        ),
        migrations.RemoveField(
            model_name='tutors',
            name='hours4',
        ),
        migrations.RemoveField(
            model_name='tutors',
            name='hours5',
        ),
        migrations.RemoveField(
            model_name='tutors',
            name='hours6',
        ),
        migrations.RemoveField(
            model_name='tutors',
            name='hours7',
        ),
        migrations.AlterField(
            model_name='tutors',
            name='classes_tutor_for',
            field=models.JSONField(default=list),
        ),
    ]
