# Generated by Django 5.0.14 on 2025-10-18 15:06

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_remove_tutors_hours1_remove_tutors_hours2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutors',
            name='classes_tutor_for',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('CSCI150', 'CSCI150'), ('CSCI151', 'CSCI151'), ('CSCI152', 'CSCI152'), ('CSCI258', 'CSCI258'), ('CSCI340', 'CSCI340'), ('CSCI447', 'CSCI447')], max_length=47),
        ),
    ]
